pipeline:
    build:
      image: docker:latest
      environment:
          - DOCKER_HOST=unix:///tmp/host.sock
          - DHUB_LOGIN=${DHUB_LOGIN}
          - DHUB_PW=${DHUB_PW}
      volumes:
          - /var/run/docker.sock:/tmp/host.sock:rw
      privileged: true
      commands:
          - docker build -t pingu/mobispring:latest .
      when:
          branch: [ master ]

    publish:
      image: plugins/docker
      username: ${DHUB_LOGIN}
      password: ${DHUB_PW}
      repo: pingu/mobispring
      tags: latest
      when:
        status: [ success ]
